-- Supabase Setup SQL
-- This script creates all necessary tables for the Joselito App.
-- Security (RLS) is disabled for all tables as requested.

-- 1. Activities Table
CREATE TABLE IF NOT EXISTS activities (
    id TEXT PRIMARY KEY,
    operario TEXT NOT NULL,
    area TEXT NOT NULL,
    formato TEXT NOT NULL,
    inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    fin TIMESTAMP WITH TIME ZONE,
    fecha DATE,
    cantidad INTEGER DEFAULT 0,
    tiempoTeorico INTEGER DEFAULT 0,
    isIncidencia BOOLEAN DEFAULT FALSE,
    tipoIncidencia TEXT,
    afectaCalidad BOOLEAN DEFAULT FALSE,
    requiereMaquina BOOLEAN DEFAULT FALSE,
    maquina TEXT,
    piezasNOK INTEGER DEFAULT 0,
    observaciones TEXT,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. History Table
CREATE TABLE IF NOT EXISTS history (
    id TEXT PRIMARY KEY,
    operario TEXT NOT NULL,
    area TEXT NOT NULL,
    formato TEXT NOT NULL,
    inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    fin TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha DATE NOT NULL,
    cantidad INTEGER DEFAULT 0,
    tiempoTeorico INTEGER DEFAULT 0,
    isIncidencia BOOLEAN DEFAULT FALSE,
    tipoIncidencia TEXT,
    afectaCalidad BOOLEAN DEFAULT FALSE,
    requiereMaquina BOOLEAN DEFAULT FALSE,
    maquina TEXT,
    piezasNOK INTEGER DEFAULT 0,
    observaciones TEXT,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Operarios Table
CREATE TABLE IF NOT EXISTS operarios (
    id TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    area TEXT,
    areas TEXT[],
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. OEE Objectives Table
CREATE TABLE IF NOT EXISTS oee_objectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area TEXT NOT NULL,
    disponibilidad NUMERIC NOT NULL,
    rendimiento NUMERIC NOT NULL,
    calidad NUMERIC NOT NULL,
    productividad NUMERIC NOT NULL,
    objetivo NUMERIC DEFAULT 0,
    merma1 NUMERIC DEFAULT 0,
    merma2 NUMERIC DEFAULT 0,
    subproducto NUMERIC DEFAULT 0,
    pph NUMERIC DEFAULT 0,
    indicator_id TEXT,
    valid_from DATE NOT NULL,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TOP60 Seguridad Table
CREATE TABLE IF NOT EXISTS top60_seguridad (
    id BIGINT PRIMARY KEY,
    fecha DATE,
    asunto TEXT,
    accion TEXT,
    responsable TEXT,
    soporte TEXT,
    fechaLanzamiento DATE,
    fechaObjetivo DATE,
    avance INTEGER,
    observaciones TEXT,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TOP60 RRHH Table
CREATE TABLE IF NOT EXISTS top60_rrhh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    area TEXT NOT NULL,
    absentismo NUMERIC DEFAULT 0,
    ausentismo NUMERIC DEFAULT 0,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. TOP60 Ausentismo Table
CREATE TABLE IF NOT EXISTS top60_ausentismo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    area TEXT NOT NULL,
    valor NUMERIC DEFAULT 0,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. TOP60 Calidad Table
CREATE TABLE IF NOT EXISTS top60_calidad (
    id TEXT PRIMARY KEY,
    semana INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    imagenes TEXT[], -- Array of base64 strings
    fechaCreacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. TOP60 IdM Table (Ideas de Mejora)
CREATE TABLE IF NOT EXISTS top60_idm (
    id TEXT PRIMARY KEY,
    idSugerencia INTEGER,
    asunto TEXT,
    accion TEXT,
    responsable TEXT,
    soporte TEXT,
    fechaLanzamiento DATE,
    fechaObjetivo DATE,
    avance INTEGER,
    observaciones TEXT,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. Master Speeds Table
CREATE TABLE IF NOT EXISTS master_speeds (
    id TEXT PRIMARY KEY,
    area TEXT NOT NULL,
    formato TEXT NOT NULL,
    tiempoTeorico INTEGER NOT NULL,
    peso NUMERIC DEFAULT 0,
    unidad TEXT DEFAULT 'unidades',
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Migration: Rename columns if they exist (PostgreSQL doesn't have RENAME COLUMN IF EXISTS directly in one line)
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='master_speeds' AND column_name='tiempo_teorico') THEN
        ALTER TABLE master_speeds RENAME COLUMN tiempo_teorico TO tiempoTeorico;
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='activities' AND column_name='tiempo_teorico') THEN
        ALTER TABLE activities RENAME COLUMN tiempo_teorico TO tiempoTeorico;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='history' AND column_name='tiempo_teorico') THEN
        ALTER TABLE history RENAME COLUMN tiempo_teorico TO tiempoTeorico;
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='incidence_master' AND column_name='afecta_calidad') THEN
        ALTER TABLE incidence_master RENAME COLUMN afecta_calidad TO afectaCalidad;
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='incidence_master' AND column_name='requiere_maquina') THEN
        ALTER TABLE incidence_master RENAME COLUMN requiere_maquina TO requiereMaquina;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='oee_objectives' AND column_name='validFrom') THEN
        ALTER TABLE oee_objectives RENAME COLUMN validFrom TO valid_from;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='oee_objectives' AND column_name='indicatorId') THEN
        ALTER TABLE oee_objectives RENAME COLUMN indicatorId TO indicator_id;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='top60_seguridad' AND column_name='fecha_lanzamiento') THEN
        ALTER TABLE top60_seguridad RENAME COLUMN fecha_lanzamiento TO fechaLanzamiento;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='top60_seguridad' AND column_name='fecha_objetivo') THEN
        ALTER TABLE top60_seguridad RENAME COLUMN fecha_objetivo TO fechaObjetivo;
    END IF;
END $$;

-- 11. Incidence Master Table
CREATE TABLE IF NOT EXISTS incidence_master (
    id TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    tipo TEXT NOT NULL,
    afectaCalidad BOOLEAN DEFAULT FALSE,
    requiereMaquina BOOLEAN DEFAULT FALSE,
    area TEXT,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. App Passwords Table
CREATE TABLE IF NOT EXISTS app_passwords (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. TOP60 Action Plan Table
CREATE TABLE IF NOT EXISTS top60_actionplan (
    id BIGINT PRIMARY KEY,
    asunto TEXT,
    accion TEXT,
    responsable TEXT,
    soporte TEXT,
    fechaLanzamiento DATE,
    fechaObjetivo DATE,
    avance INTEGER,
    observaciones TEXT,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 14. TOP15 Action Plan Table
CREATE TABLE IF NOT EXISTS top15_actionplan (
    id BIGINT PRIMARY KEY,
    asunto TEXT,
    accion TEXT,
    responsable TEXT,
    soporte TEXT,
    fechaLanzamiento DATE,
    fechaObjetivo DATE,
    avance INTEGER,
    observaciones TEXT,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 15. Authorized Users Table
CREATE TABLE IF NOT EXISTS authorized_users (
    email TEXT PRIMARY KEY,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default authorized user
INSERT INTO authorized_users (email) VALUES ('sgsjoselito2@gmail.com') ON CONFLICT (email) DO NOTHING;

-- 20. Mermas Table
CREATE TABLE IF NOT EXISTS mermas (
    id TEXT PRIMARY KEY,
    fecha DATE NOT NULL,
    area TEXT NOT NULL,
    formato TEXT NOT NULL,
    kg_entrada NUMERIC DEFAULT 0,
    kg_tacos NUMERIC DEFAULT 0,
    kg_pieles NUMERIC DEFAULT 0,
    kg_hueco NUMERIC DEFAULT 0,
    media_combi NUMERIC DEFAULT 0,
    n_envases NUMERIC DEFAULT 0,
    kg_salida NUMERIC DEFAULT 0,
    kg_merma NUMERIC DEFAULT 0,
    pct_merma1 NUMERIC DEFAULT 0,
    pct_merma2 NUMERIC DEFAULT 0,
    lastModified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Disable Row Level Security (RLS) for all tables
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE history DISABLE ROW LEVEL SECURITY;
ALTER TABLE operarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE oee_objectives DISABLE ROW LEVEL SECURITY;
ALTER TABLE top60_seguridad DISABLE ROW LEVEL SECURITY;
ALTER TABLE top60_rrhh DISABLE ROW LEVEL SECURITY;
ALTER TABLE top60_ausentismo DISABLE ROW LEVEL SECURITY;
ALTER TABLE top60_calidad DISABLE ROW LEVEL SECURITY;
ALTER TABLE top60_idm DISABLE ROW LEVEL SECURITY;
ALTER TABLE master_speeds DISABLE ROW LEVEL SECURITY;
ALTER TABLE incidence_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_passwords DISABLE ROW LEVEL SECURITY;
ALTER TABLE top60_actionplan DISABLE ROW LEVEL SECURITY;
ALTER TABLE top15_actionplan DISABLE ROW LEVEL SECURITY;
ALTER TABLE authorized_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE mermas DISABLE ROW LEVEL SECURITY;

-- Grant all privileges to anon and authenticated roles
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO authenticated;
